// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSiQgecGWJzxmnX6s2lQQ8orlwbjos13w',
    appId: '1:143910909092:web:c1db5249645074c6e5e231',
    messagingSenderId: '143910909092',
    projectId: 'jalnetra-44a79',
    authDomain: 'jalnetra-44a79.firebaseapp.com',
    storageBucket: 'jalnetra-44a79.firebasestorage.app',
    measurementId: 'G-J838PG8WZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApsaCKxPw-_iIdJ-eTE30eu84GyCcnlQ4',
    appId: '1:143910909092:android:44172b7c5e318b5be5e231',
    messagingSenderId: '143910909092',
    projectId: 'jalnetra-44a79',
    storageBucket: 'jalnetra-44a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CaaqThbNzpexgwVFhzMKBvF9JsHZWVg',
    appId: '1:143910909092:ios:76df32edbc2fda82e5e231',
    messagingSenderId: '143910909092',
    projectId: 'jalnetra-44a79',
    storageBucket: 'jalnetra-44a79.firebasestorage.app',
    iosBundleId: 'com.example.jalnetra01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CaaqThbNzpexgwVFhzMKBvF9JsHZWVg',
    appId: '1:143910909092:ios:76df32edbc2fda82e5e231',
    messagingSenderId: '143910909092',
    projectId: 'jalnetra-44a79',
    storageBucket: 'jalnetra-44a79.firebasestorage.app',
    iosBundleId: 'com.example.jalnetra01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSiQgecGWJzxmnX6s2lQQ8orlwbjos13w',
    appId: '1:143910909092:web:3c489878b28899a5e5e231',
    messagingSenderId: '143910909092',
    projectId: 'jalnetra-44a79',
    authDomain: 'jalnetra-44a79.firebaseapp.com',
    storageBucket: 'jalnetra-44a79.firebasestorage.app',
    measurementId: 'G-NCED36E201',
  );
}
